#!/bin/bash

filein() {
  FILE=""
  while read -r line; do
    FILE=$FILE$line$"\n"
  done < "$1"
}

numLines() {
  numL=0
  while read -r line; do
    numL=$(($numL + 1))
  done < "$1"
}

dims() {
  if [ "$#" -ne 1 ]; then
      echo "Incorrect number of arguments. Expected 1, got $#. Please provide 1 matrix." >&2
      exit 1
  fi
  numLines $1
  x=$numL
  grep -o $'\t' $1 > temp
  numLines temp
  y=$numL
  COLS=$((y/x))
  COLS=$(($COLS+1))
  echo $x $COLS
}

transpose() {
  if [ "$#" -ne 1 ]; then
      echo "Incorrect number of arguments. Expected 1, got $#. Please provide 1 matrix." >&2
      exit 1
  fi
  echo "TRANS"
  filein $1
}

mean() {
  if [ "$#" -ne 1 ]; then
      echo "Incorrect number of arguments. Expected 1, got $#. Please provide 1 matrix." >&2
      exit 1
  fi
  echo "MEAN"
  filein $1
}

add() {
  if [ "$#" -ne 2 ]; then
      echo "Incorrect number of arguments. Expected 2, got $#. Please provide 2 matrices." >&2
      exit 1
  fi
  dims $1 > temp
  dim1=$(cat temp)
  dims $2 > temp
  dim2=$(cat temp)
  if [[ "$dim1" != "$dim2" ]]; then
      echo "Can't add mismatched matrices." >&2
      exit 1
  fi

  filein $1
  FILE1=$FILE
  filein $2
  FILE2=$FILE
  ROWS=$x
  COLS=$COLS
  TOTALLEN=$((x * COLS))
  TOTALLEN=$((TOTALLEN - 1))
  POS1=$"0"
  POS2=$"0"

  echo "$FILE1" | grep -o "[0-9-]*[$'\t'$'\n']*" | grep -o "[0-9-]*" > temp1
  FILE1=$(cat temp1)
  echo "$FILE2" | grep -o "[0-9-]*[$'\t'$'\n']*" | grep -o "[0-9-]*" > temp2
  FILE2=$(cat temp2)
  #echo $FILE1
  while [[ $count -le $TOTALLEN ]]; do
    num1=$""
    num2=$""
    re=-?[0-9]
    while [[ ${FILE1:$POS1:1} =~ ${re} ]]; do
      num1=$num1${FILE1:$POS1:1}
      POS1=$(($POS1 + 1))
    done
    POS1=$(($POS1 + 1))
    while [[ "${FILE2:$POS2:1}" =~ ${re} ]]; do
      num2=$num2${FILE2:$POS2:1}
      POS2=$(($POS2 + 1))
    done
    POS2=$(($POS2 + 1))
    rowcount=$(($rowcount + 1))
    num3=$((num1 + num2))
    if [[ $rowcount = $COLS ]];
    then
      sep="\n"
      rowcount=$"0"
    else
      sep="\t"
    fi
    finalstr=$finalstr$num3$sep
    count=$(($count + 1))
  done
  echo -e $finalstr

  exit 0
}

multiply() {
   if [ "$#" -ne 2 ]; then
      echo "Incorrect number of arguments. Expected 2, got $#. Please provide 2 matrices." >&2
      exit 1
   fi
   dims $1 > temp
   dim1=$(cat temp)
   dims $2 > temp
   dim2=$(cat temp)
   if [[ "$dim1" != "$dim2" ]]; then
      echo "Can't add mismatched matrices." >&2
      exit 1
   fi

   filein $1
   FILE1=$FILE
   filein $2
   FILE2=$FILE
   ROWS=$x
   COLS=$COLS
   TOTALLEN=$((x * COLS))
   TOTALLEN=$((TOTALLEN - 1))
   POS1=$"0"
   POS2=$"0"

   echo "$FILE1" | grep -o "[0-9-]*[$'\t'$'\n']*" | grep -o "[0-9-]*" > temp1
   FILE1=$(cat temp1)
   echo "$FILE2" | grep -o "[0-9-]*[$'\t'$'\n']*" | grep -o "[0-9-]*" > temp2
   FILE2=$(cat temp2)
   #echo $FILE1
   while [[ $count -le $TOTALLEN ]]; do
     num1=$""
     num2=$""
     re=-?[0-9]
     while [[ ${FILE1:$POS1:1} =~ ${re} ]]; do
      num1=$num1${FILE1:$POS1:1}
      POS1=$(($POS1 + 1))
     done
     POS1=$(($POS1 + 1))
     while [[ "${FILE2:$POS2:1}" =~ ${re} ]]; do
      num2=$num2${FILE2:$POS2:1}
      POS2=$(($POS2 + 1))
     done
     POS2=$(($POS2 + 1))
     rowcount=$(($rowcount + 1))
     num3=$((num1 \* num2))
     if [[ $rowcount = $COLS ]];
     then
      sep="\n"
      rowcount=$"0"
     else
      sep="\t"
     fi
     finalstr=$finalstr$num3$sep
     count=$(($count + 1))
   done
   echo -e $finalstr
}

###MAIN###

case "$1" in
    dims|d)
      dims "${@:2}"
      exit 0
      ;;
    transpose|t)
        transpose "${@:2}"
        exit 0
        ;;
    mean|m)
        mean "${@:2}"
        exit 0
        ;;
    add|a)
        add "${@:2}"
        exit 0
        ;;
    multiply|M)
        multiply "${@:2}"
        exit 0
        ;;
    help|h)
        echo $"Usage: $0 {dims|transpose|mean|add|multiply}"
        exit 0
        ;;
    *)
        echo -e $"Command Does not Exist!\nUsage: $0 {dims|transpose|mean|add|multiply}">&2
        exit 1
esac
